experiment:
    project: "restok_l_128"
    name: "restok_l_128_run1"
    output_dir: "./output/restok_l_128_run1"
    max_train_examples: 1_281_167
    save_every: 5_000
    eval_every: 50_000
    generate_every: 5_000
    log_every: 50
    log_grad_norm_every: 1_000
    resume: True
    init_weight: ""


model:
    vq_model:
        codebook_size: 8192
        token_size: 8
        use_l2_norm: True
        commitment_cost: 0.25
        entropy_loss_ratio: 0.0
        # vit arch
        vit_enc_model_size: "large"
        vit_dec_model_size: "large"
        vit_enc_patch_size: 16
        vit_dec_patch_size: 16
        rope_base_len: 10_000
        num_latent_tokens: 128
        num_min_tokens: 4
        test_num_latent_tokens: 128
        merge_tokens: True
        hierarchy_stages: 4
        reduction_ratio: 0.5
        residual_image_tokens: True
        residual_latent_tokens: True
        learnable_latent_tokens: False
        learnable_dec_image_tokens: True
        multi_quant: True
        vae_encoder: True
        drop_latent_tokens: True
        drop_prob: 0.2
        latent_hierarchy: True
        encoder_feature_supervision: True
        decoder_feature_supervision: True
        learnable_dec_feat_tokens: True
        # hyper-param for vision foundation model alignment
        # --------------------------------------------------
        use_vf: "dinov3"
        reverse_proj: True # default: true, project from vae dim --> dinov3 dim
        # --------------------------------------------------


losses:
    dino_disc: True
    discriminator_start: 20_000
    quantizer_weight: 1.0
    discriminator_factor: 1.0
    discriminator_weight: 0.5
    perceptual_loss: "lpips"
    perceptual_weight: 1.0
    reconstruction_loss: "l2"
    reconstruction_weight: 1.0
    lecam_regularization_weight: 0.001
    # hyper-param for vision foundation model alignment
    # --------------------------------------------------
    vf_weight: 1.0
    cos_margin: 0.25
    # --------------------------------------------------


dataset:
    params:
        train_shards_path_or_url: "../datasets/imagenet-1k-wds/imagenet1k-train-{0000..1023}.tar"
        eval_shards_path_or_url: "../datasets/imagenet-1k-wds/imagenet1k-validation-{0000..0063}.tar"
        num_workers_per_gpu: 16
    preprocessing:
        random_resized_crop: True # [0.8, 1.0]
        resize_shorter_edge: 256 # only for eval
        crop_size: 256
        random_crop: True
        random_flip: True


optimizer:
    name: adamw 
    params:
        learning_rate: 1e-4
        discriminator_learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.95
        weight_decay: 1e-4


lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 5_000 # 1 epoch warmup
        end_lr: 1e-5


training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 32 # 8 GPUs, total batch size 256
    mixed_precision: "fp16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    ema_decay: 0.9999
    seed: 10086
    max_train_steps: 1_000_000
    num_generated_images: 2
    max_grad_norm: 10.0
